### ISSUE TITLE
Langchain4j plugins lack documentation and autocompletion and are marked as invalid plugins in the Editor validation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-ai#61]
### Describe the issue

![Image](https://github.com/user-attachments/assets/9e9f4753-4a59-4725-9987-03b32a8999a8)

If possible, we should ship another bugfix release before the 10th of June with a fix to this issue, as some people will demo those new plugins and others may want to reproduce. 

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
@loicmathieu, to clarify why we mark this as P0, this plugin needs to work perfectly on June 10th, so we need to find a solution and ship a fix before then. 

@brian-mulier-p, maybe you can help Loic with the autocompletion/plugin documentation issue? 

Full reproducer:

```yaml
id: document-ingestion
namespace: company.team

variables:
  embedding_model: gemini-embedding-exp-03-07
  chat_model: gemini-2.5-flash-preview-05-20

tasks:
  - id: ingest
    type: io.kestra.plugin.langchain4j.rag.IngestDocument
    disabled: true
    provider:
      type: io.kestra.plugin.langchain4j.provider.GoogleGemini
      modelName: "{{ vars.embedding_model }}"
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    embeddings:
      type: io.kestra.plugin.langchain4j.embeddings.KestraKVStore
    drop: true
    fromExternalURLs:
      - https://raw.githubusercontent.com/kestra-io/docs/refs/heads/main/content/blogs/release-0-22.md

  - id: chat_without_rag
    type: io.kestra.plugin.langchain4j.ChatCompletion
    provider:
      type: io.kestra.plugin.langchain4j.provider.GoogleGemini
      modelName: "{{ vars.chat_model }}"
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    messages:
      - type: USER
        content: Which features were released in Kestra 0.22?

  - id: chat_with_rag
    type: io.kestra.plugin.langchain4j.rag.ChatCompletion
    chatProvider:
      type: io.kestra.plugin.langchain4j.provider.GoogleGemini
      modelName: "{{ vars.chat_model }}"
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    embeddingProvider:
      type: io.kestra.plugin.langchain4j.provider.GoogleGemini
      modelName: "{{ vars.embedding_model }}"
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    embeddings:
      type: io.kestra.plugin.langchain4j.embeddings.KestraKVStore
    prompt: Which features were released in Kestra 0.22?
```
