### ISSUE TITLE
Evaluate how to have "Kestra Tasks as Tool"

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-ai#83]
It would be really nice to be able to call Kestra task parts of the tools of a given agent.

After discussion with @loicmathieu and @fdelbrayelle, this need more investigation on the technical side. Acc. to Loic there's a potential quick win.

**Comment by loicmathieu** [comment]
It will be implemented as a specific tool that will be able to call a Kestra task.

```yaml
# Other AI task properties...
tools:
  - type: io.kestra.plugin.langchain4j.tool.KestraTaskCalling
    tasks:  # List of Kestra tasks that the LLM can use
      - type: Postgres
        id: postgres
        url: xxx # task property set by the flow developer
        userName: xxx
        query: "{{agent.query}}" # task property set by the LLM when calling the tool
```

Autocompletion will work.

See the design here: https://www.notion.so/kestra-io/AI-Agent-Market-Research-23036907f7b5802abf99ec292f6b7369
